# Generated by Django on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id_conteudo', models.AutoField(db_column='ID_Conteudo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('filme', 'Filme'), ('serie', 'Série')], db_column='Tipo', max_length=20)),
                ('titulo', models.CharField(db_column='Titulo', max_length=255)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('capa_url', models.CharField(blank=True, db_column='Capa_URL', max_length=500, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Criado_em')),
            ],
            options={
                'db_table': 'conteudo',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('LIVRO', 'Livro'), ('VIDEO', 'Vídeo'), ('ARTIGO', 'Artigo Acadêmico'), ('CURSO', 'Curso'), ('OUTRO', 'Outro Formato')], max_length=20)),
                ('autor_ou_criador', models.CharField(max_length=150)),
                ('link_acesso', models.URLField(blank=True, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('login', models.CharField(db_column='Login', max_length=100, unique=True)),
                ('senha', models.CharField(db_column='Senha', help_text='Senha armazenada com hash.', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=150, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Criado_em')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id_recomendacao', models.AutoField(db_column='idRecomendacao', primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='Criado_em')),
                ('conteudo', models.ForeignKey(db_column='idConteudo', on_delete=django.db.models.deletion.CASCADE, to='api.conteudo')),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'recomendacao',
            },
        ),
        migrations.CreateModel(
            name='UsuarioConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvo_em', models.DateTimeField(auto_now_add=True, db_column='Salvo_em')),
                ('conteudo', models.ForeignKey(db_column='ID_Conteudo', on_delete=django.db.models.deletion.CASCADE, to='api.conteudo')),
                ('usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_conteudo',
                'unique_together': {('conteudo', 'usuario')},
            },
        ),
    ]
