# Generated by Django 6.0.4 on 2026-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('LIVRO', 'Livro'), ('VIDEO', 'Vídeo'), ('ARTIGO', 'Artigo Acadêmico'), ('CURSO', 'Curso'), ('OUTRO', 'Outro Formato')], max_length=20)),
                ('autor_ou_criador', models.CharField(max_length=150)),
                ('link_acesso', models.URLField(blank=True, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
